/* =========================================================
   Umer Kitab Ghar — Book Data
   All books and categories for the online bookstore
   ========================================================= */

const cover = (seed) => `https://picsum.photos/seed/${seed}/400/600`;

const CATEGORIES = [
  { id: 'fiction',         name: 'Fiction',          description: 'Imaginative worlds and captivating stories',     icon: '📚', color: 'from-amber-500 to-orange-600',  bookCount: 1248 },
  { id: 'novels',          name: 'Novels',           description: 'Long-form narratives and literary works',        icon: '📖', color: 'from-rose-500 to-red-600',     bookCount: 892  },
  { id: 'islamic',         name: 'Islamic Books',    description: 'Spiritual guidance and Islamic teachings',      icon: '☪',  color: 'from-emerald-600 to-teal-700', bookCount: 534  },
  { id: 'education',       name: 'Education',        description: 'Knowledge and learning resources',              icon: '🎓', color: 'from-blue-700 to-indigo-800', bookCount: 1567 },
  { id: 'business',        name: 'Business',         description: 'Entrepreneurship and business strategies',      icon: '💼', color: 'from-yellow-600 to-amber-700',bookCount: 723  },
  { id: 'self-development',name: 'Self Development', description: 'Personal growth and motivation',                icon: '📈', color: 'from-purple-600 to-fuchsia-700',bookCount: 645 },
  { id: 'history',         name: 'History',          description: 'Chronicles of the past and civilizations',       icon: '📜', color: 'from-stone-600 to-amber-800', bookCount: 412  },
  { id: 'technology',      name: 'Technology',       description: 'Modern science and digital innovation',         icon: '💻', color: 'from-cyan-600 to-sky-700',    bookCount: 891  },
  { id: 'children',       name: "Children's Books", description: 'Fun and educational books for kids',            icon: '🧸', color: 'from-pink-500 to-rose-600',  bookCount: 1102 },
  { id: 'poetry',          name: 'Poetry',           description: 'Beautiful verses and lyrical expressions',       icon: '🪶', color: 'from-violet-600 to-purple-700',bookCount: 287 },
];

const BOOKS = [
  { id:'b001', title:'The Midnight Library', author:'Matt Haig', category:'fiction', price:18.99, originalPrice:24.99, rating:4.7, reviewCount:2847, cover:cover('midnight-library'), description:"Between life and death there is a library, and within that library, the shelves go on forever. Every book provides a chance to try another life you could have lived. Would you have done anything different, if you had the chance to undo your regrets?", pages:304, language:'English', publisher:'Viking', year:2020, isbn:'9780525559474', isFeatured:true, isBestSeller:true, tags:['fantasy','philosophy','self-discovery'] },
  { id:'b002', title:'Where the Crawdads Sing', author:'Delia Owens', category:'fiction', price:16.49, originalPrice:19.99, rating:4.8, reviewCount:4521, cover:cover('crawdads-sing'), description:"For years, rumors of the Marsh Girl have haunted Barkley Cove, a quiet town on the North Carolina coast. So in late 1969, when handsome Chase Andrews is found dead, the locals immediately suspect Kya Clark, the so-called Marsh Girl.", pages:384, language:'English', publisher:"G.P. Putnam's Sons", year:2018, isbn:'9780735219090', isBestSeller:true, tags:['mystery','coming-of-age','nature'] },
  { id:'b003', title:'The Song of Achilles', author:'Madeline Miller', category:'fiction', price:17.99, rating:4.9, reviewCount:3214, cover:cover('song-achilles'), description:"Greece in the age of heroes. Patroclus, an awkward young prince, has been exiled to the kingdom of Phthia to be raised in the shadow of King Peleus and his golden son, Achilles.", pages:416, language:'English', publisher:'Ecco', year:2012, isbn:'9780062060624', isFeatured:true, tags:['mythology','romance','historical'] },
  { id:'b004', title:'Klara and the Sun', author:'Kazuo Ishiguro', category:'fiction', price:21.99, rating:4.5, reviewCount:1893, cover:cover('klara-sun'), description:"From her place in the store, Klara, an Artificial Friend with outstanding observational qualities, watches carefully the behavior of those who come in to browse, and of those who pass on the street outside.", pages:320, language:'English', publisher:'Knopf', year:2021, isbn:'9780525521198', isNewArrival:true, tags:['sci-fi','literary','future'] },
  { id:'b005', title:'The Great Gatsby', author:'F. Scott Fitzgerald', category:'novels', price:12.99, originalPrice:15.99, rating:4.6, reviewCount:5892, cover:cover('great-gatsby'), description:"The mysterious Jay Gatsby uses his unscrupulous wealth to win the heart of Daisy Buchanan, his former love, in this classic American novel set in the Jazz Age.", pages:180, language:'English', publisher:'Scribner', year:1925, isbn:'9780743273565', isFeatured:true, isBestSeller:true, tags:['classic','american','romance'] },
  { id:'b006', title:'Pachinko', author:'Min Jin Lee', category:'novels', price:19.99, rating:4.7, reviewCount:2104, cover:cover('pachinko'), description:"A sweeping saga of four generations of a Korean family who eventually migrates to Japan, exploring themes of identity, exile, and the consequences of historical injustice.", pages:496, language:'English', publisher:'Grand Central', year:2017, isbn:'9781455521617', isNewArrival:true, tags:['historical','family-saga','literary'] },
  { id:'b007', title:'Norwegian Wood', author:'Haruki Murakami', category:'novels', price:18.49, rating:4.5, reviewCount:3421, cover:cover('norwegian-wood'), description:"A nostalgic story of loss and burgeoning sexuality, told through the protagonist's relationships with two very different women and his reflections on the past.", pages:296, language:'English', publisher:'Vintage', year:2000, isbn:'9780375704024', tags:['literary','romance','japanese'] },
  { id:'b008', title:'The Sealed Nectar', author:'Safiur-Rahman Mubarakpuri', category:'islamic', price:24.99, rating:4.9, reviewCount:1284, cover:cover('sealed-nectar'), description:"A comprehensive biography of Prophet Muhammad (PBUH), winner of the first prize at the Muslim World League's worldwide competition on the life of the Prophet.", pages:512, language:'English', publisher:'Darussalam', year:2002, isbn:'9789960897558', isFeatured:true, isBestSeller:true, tags:['biography','prophet','history'] },
  { id:'b009', title:'Inner Dimensions of Islamic Worship', author:'Imam al-Ghazali', category:'islamic', price:16.99, rating:4.8, reviewCount:892, cover:cover('ghazali-worship'), description:"A profound exploration of the spiritual meaning and inner significance of Islamic acts of worship including prayer, fasting, almsgiving, and pilgrimage.", pages:192, language:'English', publisher:'Islamic Texts Society', year:2008, isbn:'9780946621320', tags:['spirituality','worship','classical'] },
  { id:'b010', title:'Purification of the Heart', author:'Hamza Yusuf', category:'islamic', price:19.99, rating:4.7, reviewCount:1567, cover:cover('purification-heart'), description:"Translation and commentary on Imam al-Mawlud's poem about spiritual diseases of the heart and their cures, providing timeless guidance for inner purification.", pages:224, language:'English', publisher:'Starlatch Press', year:2004, isbn:'9780970284341', isNewArrival:true, tags:['spirituality','self-improvement','classical'] },
  { id:'b011', title:'Educated', author:'Tara Westover', category:'education', price:17.99, originalPrice:22.99, rating:4.8, reviewCount:6234, cover:cover('educated-memoir'), description:"An unforgettable memoir about a young woman who, kept out of school by her radical parents, leaves her survivalist family and goes on to earn a PhD from Cambridge University.", pages:334, language:'English', publisher:'Random House', year:2018, isbn:'9780399590504', isFeatured:true, isBestSeller:true, tags:['memoir','education','biography'] },
  { id:'b012', title:'Make It Stick: The Science of Successful Learning', author:'Peter C. Brown', category:'education', price:23.99, rating:4.6, reviewCount:1456, cover:cover('make-it-stick'), description:"A powerful exploration of cognitive science findings on how learning actually works, distilling practical lessons for students, teachers, and lifelong learners.", pages:336, language:'English', publisher:'Belknap Press', year:2014, isbn:'9780674729018', isNewArrival:true, tags:['learning','cognitive-science','study-skills'] },
  { id:'b013', title:'Atomic Habits', author:'James Clear', category:'business', price:22.99, originalPrice:27.00, rating:4.9, reviewCount:12847, cover:cover('atomic-habits'), description:"The number one New York Times bestseller. No matter your goals, Atomic Habits offers a proven framework for improving every day with small, easy changes.", pages:320, language:'English', publisher:'Avery', year:2018, isbn:'9780735211292', isFeatured:true, isBestSeller:true, tags:['productivity','habits','self-improvement'] },
  { id:'b014', title:'Rich Dad Poor Dad', author:'Robert T. Kiyosaki', category:'business', price:15.99, rating:4.7, reviewCount:8921, cover:cover('rich-dad'), description:"What the rich teach their kids about money that the poor and middle class do not. The #1 personal finance book of all time, translated into dozens of languages.", pages:336, language:'English', publisher:'Plata Publishing', year:2017, isbn:'9781612680194', isBestSeller:true, tags:['finance','investing','wealth'] },
  { id:'b015', title:'Start with Why', author:'Simon Sinek', category:'business', price:19.99, rating:4.6, reviewCount:4231, cover:cover('start-with-why'), description:"The inspiring bestseller that reveals how great leaders inspire everyone to take action by starting with the fundamental question: why?", pages:256, language:'English', publisher:'Portfolio', year:2011, isbn:'9781591846444', isNewArrival:true, tags:['leadership','motivation','strategy'] },
  { id:'b016', title:'The Power of Now', author:'Eckhart Tolle', category:'self-development', price:18.99, originalPrice:24.00, rating:4.7, reviewCount:7234, cover:cover('power-of-now'), description:"A spiritual guide to finding inner peace and living fully in the present moment. Tolle's teachings have helped millions find serenity and meaning.", pages:236, language:'English', publisher:'New World Library', year:2004, isbn:'9781577314806', isFeatured:true, tags:['mindfulness','spirituality','self-help'] },
  { id:'b017', title:'Mindset: The New Psychology of Success', author:'Carol S. Dweck', category:'self-development', price:17.49, rating:4.6, reviewCount:3456, cover:cover('mindset-dweck'), description:"After decades of research, world-renowned Stanford University psychologist Carol S. Dweck discovered a simple but groundbreaking idea: the power of mindset.", pages:288, language:'English', publisher:'Ballantine Books', year:2007, isbn:'9780345472328', isNewArrival:true, tags:['psychology','growth','success'] },
  { id:'b018', title:'Sapiens: A Brief History of Humankind', author:'Yuval Noah Harari', category:'history', price:22.99, originalPrice:28.00, rating:4.8, reviewCount:9234, cover:cover('sapiens'), description:"From a renowned historian comes a groundbreaking narrative of humanity's creation and evolution that explores the ways in which biology and history have defined us.", pages:464, language:'English', publisher:'Harper', year:2015, isbn:'9780062316097', isFeatured:true, isBestSeller:true, tags:['anthropology','civilization','evolution'] },
  { id:'b019', title:'Guns, Germs, and Steel', author:'Jared Diamond', category:'history', price:21.99, rating:4.5, reviewCount:4567, cover:cover('guns-germs-steel'), description:"A Pulitzer Prize-winning analysis of how Western societies developed technologies and immunity that allowed them to dominate much of the world.", pages:528, language:'English', publisher:'W. W. Norton', year:2005, isbn:'9780393061314', tags:['civilization','geography','anthropology'] },
  { id:'b020', title:'Clean Code', author:'Robert C. Martin', category:'technology', price:34.99, originalPrice:39.99, rating:4.6, reviewCount:2341, cover:cover('clean-code'), description:"A handbook of agile software craftsmanship. Even bad code can function, but if code isn't clean, it can cost a development organization dearly.", pages:464, language:'English', publisher:'Prentice Hall', year:2008, isbn:'9780132350884', isFeatured:true, isBestSeller:true, tags:['programming','software','best-practices'] },
  { id:'b021', title:'Artificial Intelligence: A Guide for Thinking Humans', author:'Melanie Mitchell', category:'technology', price:24.99, rating:4.5, reviewCount:893, cover:cover('ai-guide'), description:"An accessible and authoritative guide to what AI can and cannot do, separating the reality from the hype and explaining what the future may hold.", pages:368, language:'English', publisher:'Farrar, Straus and Giroux', year:2019, isbn:'9780374257835', isNewArrival:true, tags:['ai','machine-learning','future'] },
  { id:'b022', title:'The Very Hungry Caterpillar', author:'Eric Carle', category:'children', price:9.99, rating:4.9, reviewCount:12453, cover:cover('hungry-caterpillar'), description:"A beloved classic that has charmed generations of readers. Follow the very hungry caterpillar as he eats his way through the pages of this beautiful book.", pages:26, language:'English', publisher:'Philomel Books', year:1994, isbn:'9780399226908', isFeatured:true, isBestSeller:true, tags:['picture-book','classic','nature'] },
  { id:'b023', title:'Where the Wild Things Are', author:'Maurice Sendak', category:'children', price:11.99, rating:4.8, reviewCount:8721, cover:cover('wild-things'), description:"When Max puts on his wolf suit and misbehaves, he's sent to bed without supper. His room transforms into a forest and he sails to the land of the wild things.", pages:48, language:'English', publisher:'HarperCollins', year:1988, isbn:'9780060254926', isNewArrival:true, tags:['picture-book','classic','imagination'] },
  { id:'b024', title:'Milk and Honey', author:'Rupi Kaur', category:'poetry', price:14.99, originalPrice:18.99, rating:4.5, reviewCount:5621, cover:cover('milk-honey'), description:"A collection of poetry and prose about survival, the experience of violence, abuse, love, loss, and femininity, divided into four chapters.", pages:208, language:'English', publisher:'Andrews McMeel', year:2015, isbn:'9781449478425', isFeatured:true, isBestSeller:true, tags:['contemporary','feminism','modern'] },
  { id:'b025', title:'The Sun and Her Flowers', author:'Rupi Kaur', category:'poetry', price:15.99, rating:4.6, reviewCount:3421, cover:cover('sun-flowers'), description:"From the #1 New York Times bestselling author of milk and honey comes a long-awaited second collection of poetry that takes readers through a journey of the most difficult moments of life.", pages:248, language:'English', publisher:'Andrews McMeel', year:2017, isbn:'9781501172712', isNewArrival:true, tags:['contemporary','growth','modern'] },
  { id:'b026', title:'The Alchemist', author:'Paulo Coelho', category:'fiction', price:16.99, rating:4.7, reviewCount:7892, cover:cover('alchemist'), description:"A shepherd boy named Santiago travels from his homeland in Spain to the Egyptian desert in search of a treasure buried near the pyramids.", pages:208, language:'English', publisher:'HarperOne', year:2014, isbn:'9780062315007', isFeatured:true, isBestSeller:true, tags:['philosophy','adventure','wisdom'] },
  { id:'b027', title:'Deep Work', author:'Cal Newport', category:'business', price:21.99, rating:4.7, reviewCount:3892, cover:cover('deep-work'), description:"Rules for focused success in a distracted world. An indispensable guide to anyone seeking focused success in a distracted world.", pages:296, language:'English', publisher:'Grand Central', year:2016, isbn:'9781455586691', isNewArrival:true, tags:['productivity','focus','work'] },
  { id:'b028', title:'1984', author:'George Orwell', category:'novels', price:11.99, rating:4.7, reviewCount:10432, cover:cover('1984-orwell'), description:"A startling and haunting novel of a man's rebellion against the totalitarian state that controls every aspect of his life, including his thoughts.", pages:328, language:'English', publisher:'Signet Classic', year:1961, isbn:'9780451524935', isBestSeller:true, tags:['dystopia','classic','political'] },
  { id:'b029', title:'The Silent Patient', author:'Alex Michaelides', category:'fiction', price:17.99, rating:4.5, reviewCount:4123, cover:cover('silent-patient'), description:"A psychological thriller about a woman who shoots her husband five times and then never speaks another word, and the psychotherapist obsessed with uncovering her motive.", pages:336, language:'English', publisher:'Celadon Books', year:2019, isbn:'9781250301697', isNewArrival:true, tags:['thriller','mystery','psychological'] },
  { id:'b030', title:'The Wright Brothers', author:'David McCullough', category:'history', price:19.99, rating:4.7, reviewCount:2103, cover:cover('wright-brothers'), description:"The dramatic story-behind-the-story about the courageous brothers who taught the world how to fly, told by two-time Pulitzer Prize winner David McCullough.", pages:336, language:'English', publisher:'Simon & Schuster', year:2015, isbn:'9781476728759', isFeatured:true, tags:['biography','aviation','american'] },
];

// Helpers
function getBookById(id) { return BOOKS.find(b => b.id === id); }
function getBooksByCategory(catId) { return BOOKS.filter(b => b.category === catId); }
function getFeaturedBooks() { return BOOKS.filter(b => b.isFeatured); }
function getBestSellers() { return BOOKS.filter(b => b.isBestSeller); }
function getNewArrivals() { return BOOKS.filter(b => b.isNewArrival); }
function getRelatedBooks(book, limit = 4) {
  return BOOKS.filter(b => b.category === book.category && b.id !== book.id).slice(0, limit);
}
function searchBooks(query) {
  const q = query.toLowerCase().trim();
  if (!q) return BOOKS;
  return BOOKS.filter(b =>
    b.title.toLowerCase().includes(q) ||
    b.author.toLowerCase().includes(q) ||
    b.category.toLowerCase().includes(q) ||
    b.tags.some(t => t.toLowerCase().includes(q))
  );
}
function getAllAuthors() {
  return Array.from(new Set(BOOKS.map(b => b.author))).sort();
}
function getCategoryById(id) {
  return CATEGORIES.find(c => c.id === id);
}

// Expose globally
window.BOOKS = BOOKS;
window.CATEGORIES = CATEGORIES;
window.getBookById = getBookById;
window.getBooksByCategory = getBooksByCategory;
window.getFeaturedBooks = getFeaturedBooks;
window.getBestSellers = getBestSellers;
window.getNewArrivals = getNewArrivals;
window.getRelatedBooks = getRelatedBooks;
window.searchBooks = searchBooks;
window.getAllAuthors = getAllAuthors;
window.getCategoryById = getCategoryById;
